"""
Ledgergut standalone router — dedicated mock-OCR extract and stub package generation.

Endpoints:
  POST /ledgergut/extract                — upload receipt, get extracted fields
  POST /ledgergut/generate-reimbursement — submit reviewed data, get stub package
  GET  /ledgergut/download/{filename}    — download generated package
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.models.case import ExtractedData
from app.services import ledgergut as ledgergut_service

router = APIRouter(prefix="/ledgergut", tags=["ledgergut"])

UPLOAD_DIR = os.environ.get("LEDGERGUT_UPLOAD_DIR", "data/ledgergut/uploads")
OUTPUT_DIR = os.environ.get("LEDGERGUT_OUTPUT_DIR", "data/ledgergut/output")


# ---------------------------------------------------------------------------
# Extract
# ---------------------------------------------------------------------------


@router.post("/extract", response_model=ExtractedData)
async def extract_receipt(file: UploadFile = File(...)) -> ExtractedData:
    """
    Accept a receipt upload, run mock OCR, and return extracted fields.

    Supports PDF (text-layer), plain text (.txt, .csv), and image files
    (returns low-confidence placeholder with manual-fill warnings).
    """
    os.makedirs(UPLOAD_DIR, exist_ok=True)

    uid = str(uuid.uuid4())[:8]
    safe_name = f"{uid}_{os.path.basename(file.filename or 'upload')}"
    dest = os.path.join(UPLOAD_DIR, safe_name)

    content = await file.read()
    with open(dest, "wb") as fh:
        fh.write(content)

    return ledgergut_service.extract(dest)


# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------


class ReimbursementRequest(BaseModel):
    vendor: Optional[str] = None
    date: Optional[str] = None
    total: Optional[float] = None
    currency: str = "USD"
    purpose: Optional[str] = None
    notes: Optional[str] = None


class ReimbursementResponse(BaseModel):
    filename: str
    download_path: str


@router.post("/generate-reimbursement", response_model=ReimbursementResponse)
def generate_reimbursement(payload: ReimbursementRequest) -> ReimbursementResponse:
    """
    Accept reviewed expense data and produce a stub reimbursement package.

    Returns the filename and a download path so the client can fetch the file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    uid = str(uuid.uuid4())[:8]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    filename = f"reimbursement_{uid}.txt"
    filepath = os.path.join(OUTPUT_DIR, filename)

    vendor = payload.vendor or "Unknown Vendor"
    date = payload.date or "Unknown Date"
    total = payload.total or 0.00
    currency = payload.currency or "USD"
    purpose = payload.purpose or "General business expense"
    notes = payload.notes or ""

    lines = [
        "=" * 60,
        "        GOBLIN BLACK OFFICE — REIMBURSEMENT REQUEST",
        "=" * 60,
        f"Generated    : {now}",
        "Processed by : Ledgergut, Senior Reimbursement Operative",
        "-" * 60,
        "EXPENSE DETAILS",
        "-" * 60,
        f"Vendor       : {vendor}",
        f"Date         : {date}",
        f"Amount       : {currency} {total:.2f}",
        f"Purpose      : {purpose}",
    ]

    if notes:
        lines.append(f"Notes        : {notes}")

    lines += [
        "=" * 60,
        "This document was generated by Goblin Black Office.",
        "Ledgergut takes no responsibility for receipts written in",
        "illegible goblin-scratch or suspiciously round numbers.",
        "=" * 60,
        "",
    ]

    Path(filepath).write_text("\n".join(lines))

    return ReimbursementResponse(
        filename=filename,
        download_path=f"/ledgergut/download/{filename}",
    )


# ---------------------------------------------------------------------------
# Download
# ---------------------------------------------------------------------------


@router.get("/download/{filename}")
def download_package(filename: str) -> FileResponse:
    """Download a generated reimbursement package by filename."""
    safe_filename = os.path.basename(filename)
    filepath = os.path.join(OUTPUT_DIR, safe_filename)
    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="File not found.")
    return FileResponse(filepath, filename=safe_filename)
