"""
Package generation for receipt_reimbursement cases.

Produces a plain-text reimbursement summary that can be downloaded by the
user.  Future goblins can replace this with PDF, DOCX, or HTML generation.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from app.models.case import Case


def generate_reimbursement_package(case: Case, output_dir: str) -> str:
    """
    Write a reimbursement summary file and return its file path.

    The output is a structured plain-text document suitable for email
    attachment or printing.
    """
    os.makedirs(output_dir, exist_ok=True)

    rd = case.reviewedData
    ed = case.extractedData

    vendor = (rd and rd.vendor) or (ed and ed.vendor) or "Unknown Vendor"
    date = (rd and rd.date) or (ed and ed.date) or "Unknown Date"
    total = (rd and rd.total) or (ed and ed.total) or 0.00
    currency = (rd and rd.currency) or (ed and ed.currency) or "USD"
    purpose = (rd and rd.purpose) or "General business expense"
    notes = (rd and rd.notes) or ""

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    filename = f"reimbursement_{case.id[:8]}.txt"
    filepath = os.path.join(output_dir, filename)

    lines = [
        "=" * 60,
        "        GOBLIN BLACK OFFICE — REIMBURSEMENT REQUEST",
        "=" * 60,
        f"Case ID      : {case.id}",
        f"Generated    : {now}",
        f"Processed by : Ledgergut, Senior Reimbursement Operative",
        "-" * 60,
        "EXPENSE DETAILS",
        "-" * 60,
        f"Vendor       : {vendor}",
        f"Date         : {date}",
        f"Amount       : {currency} {total:.2f}",
        f"Purpose      : {purpose}",
    ]

    if notes:
        lines += [f"Notes        : {notes}"]

    lines += [
        "-" * 60,
        "EVIDENCE",
        "-" * 60,
    ]

    for f in case.evidenceFiles:
        lines.append(f"  • {Path(f).name}")

    if case.extractedData:
        lines += [
            "-" * 60,
            f"Extraction confidence : {case.extractedData.confidence * 100:.0f}%",
        ]
        if case.extractedData.warnings:
            lines.append("Extraction warnings:")
            for w in case.extractedData.warnings:
                lines.append(f"  ⚠  {w}")

    lines += [
        "=" * 60,
        "This document was generated by Goblin Black Office.",
        "Ledgergut takes no responsibility for receipts written in",
        "illegible goblin-scratch or suspiciously round numbers.",
        "=" * 60,
        "",
    ]

    Path(filepath).write_text("\n".join(lines))
    return filepath
